
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'CCF99DA21E2B59E4544DC02FE7AD2CA3'
    
_lr_action_items = {'VERSION':([0,],[2,]),'$end':([1,3,8,],[0,-1,-2,]),'NUMBER':([2,5,7,],[4,6,8,]),'DOT':([4,6,],[5,7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'version':([0,],[1,]),'versionstring':([2,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> version","S'",1,None,None,None),
  ('version -> VERSION versionstring','version',2,'p_version','plytest.py',120),
  ('versionstring -> NUMBER DOT NUMBER DOT NUMBER','versionstring',5,'p_versionstring','plytest.py',126),
]
